# Generated by Django 3.1.4 on 2021-01-08 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mylistmusic',
            old_name='storage_mylist',
            new_name='mylist',
        ),
    ]
